signatures = ["1ca8dcc0bed3cbd872d2cb791200c0292ca9975768a82d676b8b424fb65b5295"]
source = "Google"

staticDeps = ["app.grapheneos.gmscompat >= 1007", "android >= 34"]
deps = ["com.google.android.gms"]

description = """
Official release of Android Auto without modifications.
<br><br>
After installation, Android Auto has to be set up from the <b>Settings&nbsp;> Apps&nbsp;> Sandboxed Google
Play&nbsp;> Android Auto</b> screen.
<br><br>
To set up Android Auto in Private Space, go to <b>Settings&nbsp;> Security and privacy&nbsp;> Private 
Space&nbsp;> Sandboxed Google Play&nbsp;> Android Auto</b>
"""
