signatures = ["e5044303e85b4cceaae00ecf8823c9c6f937a8e3a2fb632ec9fa45b2c33b4bd1"]
source = "GrapheneOS"
hasFsVeritySignatures = true

isTopLevel = false

noCode = true

staticDeps = ["app.grapheneos.AppCompatConfig >= 1"]

description = """
<p>AppCompatConfig is a part of GrapheneOS. It's a file that specifies compatibility of some apps
with the optional GrapheneOS per-app exploit protection features, which allows to automatically
enable or disable them by default.</p>

<p>The main purpose of AppCompatConfig is to enable additional exploit protections for popular apps
that are known to be compatible with them.</p>

<p>Automatic disabling of exploit protection features can be turned off via <b>Settings&nbsp;>
Security&nbsp;> Automatic exploit protection compatibility mode</b> toggle.</p>
"""
